package com.jyh.kxt.base.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jyh.kxt.av.json.VideoListJson;
import com.jyh.kxt.base.dao.EmojeBean;
import com.jyh.kxt.main.json.flash.FlashJson;
import com.jyh.kxt.main.json.NewsJson;
import com.jyh.kxt.base.dao.MarkBean;
import com.jyh.kxt.trading.json.ViewPointTradeBean;
import com.jyh.kxt.chat.json.ChatRoomJson;

import com.jyh.kxt.base.dao.VideoListJsonDao;
import com.jyh.kxt.base.dao.EmojeBeanDao;
import com.jyh.kxt.base.dao.FlashJsonDao;
import com.jyh.kxt.base.dao.NewsJsonDao;
import com.jyh.kxt.base.dao.MarkBeanDao;
import com.jyh.kxt.base.dao.ViewPointTradeBeanDao;
import com.jyh.kxt.base.dao.ChatRoomJsonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoListJsonDaoConfig;
    private final DaoConfig emojeBeanDaoConfig;
    private final DaoConfig flashJsonDaoConfig;
    private final DaoConfig newsJsonDaoConfig;
    private final DaoConfig markBeanDaoConfig;
    private final DaoConfig viewPointTradeBeanDaoConfig;
    private final DaoConfig chatRoomJsonDaoConfig;

    private final VideoListJsonDao videoListJsonDao;
    private final EmojeBeanDao emojeBeanDao;
    private final FlashJsonDao flashJsonDao;
    private final NewsJsonDao newsJsonDao;
    private final MarkBeanDao markBeanDao;
    private final ViewPointTradeBeanDao viewPointTradeBeanDao;
    private final ChatRoomJsonDao chatRoomJsonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoListJsonDaoConfig = daoConfigMap.get(VideoListJsonDao.class).clone();
        videoListJsonDaoConfig.initIdentityScope(type);

        emojeBeanDaoConfig = daoConfigMap.get(EmojeBeanDao.class).clone();
        emojeBeanDaoConfig.initIdentityScope(type);

        flashJsonDaoConfig = daoConfigMap.get(FlashJsonDao.class).clone();
        flashJsonDaoConfig.initIdentityScope(type);

        newsJsonDaoConfig = daoConfigMap.get(NewsJsonDao.class).clone();
        newsJsonDaoConfig.initIdentityScope(type);

        markBeanDaoConfig = daoConfigMap.get(MarkBeanDao.class).clone();
        markBeanDaoConfig.initIdentityScope(type);

        viewPointTradeBeanDaoConfig = daoConfigMap.get(ViewPointTradeBeanDao.class).clone();
        viewPointTradeBeanDaoConfig.initIdentityScope(type);

        chatRoomJsonDaoConfig = daoConfigMap.get(ChatRoomJsonDao.class).clone();
        chatRoomJsonDaoConfig.initIdentityScope(type);

        videoListJsonDao = new VideoListJsonDao(videoListJsonDaoConfig, this);
        emojeBeanDao = new EmojeBeanDao(emojeBeanDaoConfig, this);
        flashJsonDao = new FlashJsonDao(flashJsonDaoConfig, this);
        newsJsonDao = new NewsJsonDao(newsJsonDaoConfig, this);
        markBeanDao = new MarkBeanDao(markBeanDaoConfig, this);
        viewPointTradeBeanDao = new ViewPointTradeBeanDao(viewPointTradeBeanDaoConfig, this);
        chatRoomJsonDao = new ChatRoomJsonDao(chatRoomJsonDaoConfig, this);

        registerDao(VideoListJson.class, videoListJsonDao);
        registerDao(EmojeBean.class, emojeBeanDao);
        registerDao(FlashJson.class, flashJsonDao);
        registerDao(NewsJson.class, newsJsonDao);
        registerDao(MarkBean.class, markBeanDao);
        registerDao(ViewPointTradeBean.class, viewPointTradeBeanDao);
        registerDao(ChatRoomJson.class, chatRoomJsonDao);
    }
    
    public void clear() {
        videoListJsonDaoConfig.clearIdentityScope();
        emojeBeanDaoConfig.clearIdentityScope();
        flashJsonDaoConfig.clearIdentityScope();
        newsJsonDaoConfig.clearIdentityScope();
        markBeanDaoConfig.clearIdentityScope();
        viewPointTradeBeanDaoConfig.clearIdentityScope();
        chatRoomJsonDaoConfig.clearIdentityScope();
    }

    public VideoListJsonDao getVideoListJsonDao() {
        return videoListJsonDao;
    }

    public EmojeBeanDao getEmojeBeanDao() {
        return emojeBeanDao;
    }

    public FlashJsonDao getFlashJsonDao() {
        return flashJsonDao;
    }

    public NewsJsonDao getNewsJsonDao() {
        return newsJsonDao;
    }

    public MarkBeanDao getMarkBeanDao() {
        return markBeanDao;
    }

    public ViewPointTradeBeanDao getViewPointTradeBeanDao() {
        return viewPointTradeBeanDao;
    }

    public ChatRoomJsonDao getChatRoomJsonDao() {
        return chatRoomJsonDao;
    }

}
