package com.jyh.kxt.base.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jyh.kxt.av.json.VideoListJson;
import com.jyh.kxt.base.dao.EmojeBean;
import com.jyh.kxt.main.json.flash.FlashJson;
import com.jyh.kxt.main.json.NewsJson;

import com.jyh.kxt.base.dao.VideoListJsonDao;
import com.jyh.kxt.base.dao.EmojeBeanDao;
import com.jyh.kxt.base.dao.FlashJsonDao;
import com.jyh.kxt.base.dao.NewsJsonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoListJsonDaoConfig;
    private final DaoConfig emojeBeanDaoConfig;
    private final DaoConfig flashJsonDaoConfig;
    private final DaoConfig newsJsonDaoConfig;

    private final VideoListJsonDao videoListJsonDao;
    private final EmojeBeanDao emojeBeanDao;
    private final FlashJsonDao flashJsonDao;
    private final NewsJsonDao newsJsonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoListJsonDaoConfig = daoConfigMap.get(VideoListJsonDao.class).clone();
        videoListJsonDaoConfig.initIdentityScope(type);

        emojeBeanDaoConfig = daoConfigMap.get(EmojeBeanDao.class).clone();
        emojeBeanDaoConfig.initIdentityScope(type);

        flashJsonDaoConfig = daoConfigMap.get(FlashJsonDao.class).clone();
        flashJsonDaoConfig.initIdentityScope(type);

        newsJsonDaoConfig = daoConfigMap.get(NewsJsonDao.class).clone();
        newsJsonDaoConfig.initIdentityScope(type);

        videoListJsonDao = new VideoListJsonDao(videoListJsonDaoConfig, this);
        emojeBeanDao = new EmojeBeanDao(emojeBeanDaoConfig, this);
        flashJsonDao = new FlashJsonDao(flashJsonDaoConfig, this);
        newsJsonDao = new NewsJsonDao(newsJsonDaoConfig, this);

        registerDao(VideoListJson.class, videoListJsonDao);
        registerDao(EmojeBean.class, emojeBeanDao);
        registerDao(FlashJson.class, flashJsonDao);
        registerDao(NewsJson.class, newsJsonDao);
    }
    
    public void clear() {
        videoListJsonDaoConfig.clearIdentityScope();
        emojeBeanDaoConfig.clearIdentityScope();
        flashJsonDaoConfig.clearIdentityScope();
        newsJsonDaoConfig.clearIdentityScope();
    }

    public VideoListJsonDao getVideoListJsonDao() {
        return videoListJsonDao;
    }

    public EmojeBeanDao getEmojeBeanDao() {
        return emojeBeanDao;
    }

    public FlashJsonDao getFlashJsonDao() {
        return flashJsonDao;
    }

    public NewsJsonDao getNewsJsonDao() {
        return newsJsonDao;
    }

}
